#!/bin/bash

SETUP="$1"

setup_linux() {
	local VERSION="$1"
	local LINUX="$2"

	case "${VERSION}" in
		make|--make|-m)
			cp make/linux/Makefile .
			;;
		build|--build|-b)
			cp make/build/${LINUX}/Makefile .
			;;
		*)
			echo "Wrong Operant" ;;
	esac

	make
}

setup_termux() {
	local VERSION="$1"
	local MANAGER="$2"

	case "${VERSION}" in
		make|--make|-m)
			cp make/termux/Makefile .
			;;
		build|--build|-b)
			cp make/build/termux/${MANAGER}/Makefile .
			;;
		*)
			echo "Wrong Operant" ;;
	esac

	make
}

case "${SETUP}" in
	linux|--linux|-l)
		setup_linux "${@:2}" ;;
	termux|--termux|-t)
		setup_termux "${@:2}" ;;
	-lm)
		setup_linux make ;;
	-lba)
		setup_linux build archlinux ;;
	-lbd)
		setup_linux build debian ;;
	-tm)
		setup_termux make ;;
	-tba)
		setup_termux build apt ;;
	-tbp)
		setup_termux build pacman ;;
	*)
		setup_linux make ;;
esac
